name: bencanaku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  curved_labeled_navigation_bar: ^2.0.6
  flutter:
    sdk: flutter
  flutter_login: ^6.0.0
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  http: ^1.2.1
  geocoding: ^4.0.0
  shared_preferences: ^2.5.3
  sensors_plus: ^6.1.2
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  timezone: ^0.10.1
  image_picker: ^1.2.0
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
